---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: F5 AI Guardrails Policy
    category: Custom
    description: This extension defines a custom policy for F5 AI Guardrails, allowing users to send requests to an external service for scanning and analysis.
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    externalService:
      type: string
      format: service
      description: The external service to which the request will be sent. 
    endpointPath:
      type: string
      default: /backend/v1/scans
      description: The path of the endpoint to which the request will be sent.
    secretToken:
      type: string
      description: The secret token for authenticating the request.
      default: my_secret_token_123
      "@context": {
        "@characteristics": [
          "security:sensitive"
        ]
      }

  required:
    - externalService
    - endpointPath
    - secretToken
